### ISSUE TITLE
Confirm support for Solr 8

### ISSUE THREAD

**Issue by AronNovak** [geerlingguy/ansible-role-solr#110]
```
- name: Solr server
  hosts: all
  remote_user: root

  tasks:
  - name: Java JDK
    include_role:
      name: geerlingguy.java

  - name: Solr server
    include_role:
      name: geerlingguy.solr
    vars:
      solr_cores:
        - "moo"
      solr_version: "8.2.0"
```

This one works well, possibly we can state that the role has at least some kind of Solr 8 support (as well).
