### ISSUE TITLE
Solr service not installing with solr version < 5

### ISSUE THREAD

**Issue by Rade333** [geerlingguy/ansible-role-solr#53]
Hey,

My playbook:

```
---
- hosts: all
  become: yes
  roles:
    - { role: geerlingguy.java }
    - { role: geerlingguy.solr, solr_version: "4.10.4" }
```

Fails on this task:

```
TASK [geerlingguy.solr : Ensure solr is started and enabled on boot.] **********
fatal: [192.168.104.11]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'solr'\": "}
```

See full output here: http://pastebin.com/w3CSYCSa

I'm using your geerlingguy/ubuntu1604 vagrant box, ansible 2.2.0.0 and release 3.4.1 of this role.

I was able to work around the issue if I run this command in the vagrant machine:

```
sudo update-rc.d solr defaults
```

Any thoughts?
