### ISSUE TITLE
Solr version < 5 doesn't read solr cores from the correct path

### ISSUE THREAD

**Issue by Rade333** [geerlingguy/ansible-role-solr#57]
When installing Solr version 4.10.4 with the latest release of this role, Solr doesn't read the solr cores from the correct path, which would be `{{ solr_home }}` (defaults to `/var/solr`).

Rather the cores are read from /opt/solr/node1/solr, that is from the solr install path. See screenshot from the solr admin tool:
![Alt text](https://monosnap.com/file/yF88WdTsoPGyHUYDjXk37IxtJvwGEj.png)

I'm using geerlingguy/ubuntu1604 vagrant box, ansible 2.2.0.0 and release 3.4.2 of this role.

My playbook is

```
---
- hosts: all
  sudo: yes
  vars:
    solr_version: "4.10.4"
    solr_cores:
      - common
  roles:
    - geerlingguy.java
    - geerlingguy.solr
  post_tasks:
    - name: Remove default core
      file:
        path: "{{ solr_home }}/collection1"
        state: absent
      when: solr_cores is defined

    - name: Create solr core paths
      file:
        path: "{{ solr_home }}/{{ item }}"
        state: directory
        owner: "{{ solr_user }}"
        group: "{{ solr_user }}"
      with_items: "{{ solr_cores }}"
      when: solr_cores is defined

    - name: Copy solr core configs
      copy:
        src: "solr-cores/{{ item }}/"
        dest: "{{ solr_home }}/{{ item }}"
        owner: "{{ solr_user }}"
        group: "{{ solr_user }}"
      with_items: "{{ solr_cores }}"
      notify: restart solr
      when: solr_cores is defined
```

The core I'm using looks like this
![Alt text](https://monosnap.com/file/DeLxIcqVmbNW1BNKTKsbJCyF8OZ0k6.png)

core.properties:

```
name=common
```

The `conf` dir is identical to the one from Drupal's search_api_solr module, http://cgit.drupalcode.org/search_api_solr/tree/solr-conf/4.x
