### ISSUE TITLE
Combine 'Download' and 'Expand' solr tasks using unarchive

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-solr#58]
Since 2.0 is pretty much everywhere, we can use `unarchive`s ability to download and expand-into-place the Solr archive.

Currently, the download file sits on the system after the role is finished, but that's annoying... it's like 150MB! And it's causing downstream projects to also be larger than necessary. See, for example: https://github.com/geerlingguy/docker-image-solr/issues/5

Basically, with Ansible 2.x, we should be able to combine these two tasks:

```yaml
- name: Download Solr.
  get_url:
    url: "{{ solr_mirror }}/lucene/solr/{{ solr_version }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    force: no

- name: Expand Solr.
  unarchive:
    src: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}"
    creates: "{{ solr_workspace }}/{{ solr_filename }}/CHANGES.txt"
    copy: no
```

Also, related: https://github.com/geerlingguy/ansible-role-solr/issues/14
