### ISSUE TITLE
Question about solr core creation on <5

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-solr#68]
Just a quick question as I'm in the process of working out how to automate solr cores on installations using major versions 3-6.

The solr core creation script only came into place officially in version 5, what would be your recommended method of automation for versions 3 and 4?

I understand this has no real chance of becoming a part of the workflow of this role, but I believe the question is worth asking.

**Comment by geerlingguy** [comment]
@fubarhouse - Yeah... I've actually been trying to find a nice simple way to do it for one of my own projects too. It was never super easy to add cores in 3.x/4.x, but the basic way I'm doing it now is:

  - use a templated `solr.xml` file with all the cores listed.
  - manually modify the `<dataDir>` in each core's `solrconfig.xml` file
  - copy things into the right places
  - cross fingers and hope it all works!

**Comment by longwave** [comment]
Solr 4.4 through 4.10 have automatic core discovery, for these versions you have to:

* create a core directory manually containing `conf` and `data`
* manually copy your config into `conf` (ensure there is no `<dataDir>` set in `solrconfig.xml`)
* place `core.properties` containing `name=[your core name]` in the core directory

My Ansible playbook for a Solr 4.8.1 server with 3 cores on an EC2 instance looks like this:

```
---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - geerlingguy.java
    - geerlingguy.solr

  vars:
    solr_version: 4.8.1
    cores:
      - app1
      - app2
      - app3

  tasks:
    - name: Mount EBS volume
      mount:
        name: /mnt/solr
        src: /dev/xvdf
        fstype: ext4
        opts: defaults,nofail
        state: present

    - name: Create Solr core
      lineinfile:
        path: "/var/solr/{{ item }}/core.properties"
        regexp: '^name='
        line: 'name={{ item }}'
        create: yes
        owner: solr
        group: solr
        mode: 0644
      with_items: "{{ cores }}"

    - name: Deploy Solr config
      copy:
        src: "files/{{ item }}/solr/"
        dest: "/var/solr/{{ item }}/conf"
        owner: solr
        group: solr
        mode: 0644
      with_items: "{{ cores }}"

    - name: Symlink Solr data
      file:
        src: "/mnt/solr/{{ item }}"
        dest: "/var/solr/{{ item }}/data"
        force: yes
        owner: solr
        group: solr
        state: link
      with_items: "{{ cores }}"
```

**Comment by simesy** [comment]
Can anyone offer a task file that creates a new core from Drupal's search_api_solr config? I had it working for 5 but struggling a bit with 4.

**Comment by fubarhouse** [comment]
@simesy have you tried the playbook by @longwave?

You'd need a Solr 4 instace for it to work, but it looks good. You may also need to template a file for the cores.

I'll have anotherlook today - I have not had a lot of Solr 6 success in local drupal development in recent weeks.

**Comment by simesy** [comment]
Thanks fubarhouse, i'll have a looksee.

**Comment by simesy** [comment]
Oh you mean up there. yeah i manually tried those steps that failed, but since then I went on a long loop of other things. Going to try again now.

**Comment by fubarhouse** [comment]
I could look into it in that case, the most critical piece is templating a single file with the core configs.

I’ve no problem with templating it, but longer term management isn’t flexible outside of Ansible and as you’ve seen in person our Jenkins workflows capitalise on that flexibility. I haven’t invested in Solr 4 config management yet...

I would use geerlingguy’s recommendation in doing this, but no guarantees though, I’m pressed for time outside work hours at the moment.

**Comment by simesy** [comment]
i think the templating thing is fine, it's installing any core and getting anything to show on http.../solr/ :)

**Comment by simesy** [comment]
Ok, solr hadn't started properly. Making more sense now.

**Comment by simesy** [comment]
For reference these are my config and rudimentary steps. With:

- core.properties containing `name=MYCORE`
- `sudo /var/init.d/solr start`
- then visit MYSITE.vm:8983/solr/#/MYCORE

```
solr_version: "4.5.1"
solr_xms: "64M"
solr_xmx: "128M"
solr_remove_cruft: true
solr_install_path: /opt/solr
solr_connect_host: MYSITE.vm
```

```
  - name: Setup Drupal solr config
    copy:
      src: ../docroot/modules/contrib/search_api_solr/solr-conf/4.x/
      dest: /var/solr/MYCORE/conf/
      owner: solr
      group: solr
      mode: 0755
    when: stat_solr.stat.exists == False

  - name: Set discoverable core property file
    template:
      src: assets/core.properties
      dest: "/var/solr/MYCORE/"
      owner: solr
      group: solr
      mode: 0755
```


Thanks @longwave !
