### ISSUE TITLE
Ubuntu 18.04 LTS - init script issue

### ISSUE THREAD

**Issue by AronNovak** [geerlingguy/ansible-role-solr#96]
```
TASK [geerlingguy.solr : Run systemd daemon_reload (RHEL 7 workaround).] ****************************************************
skipping: [192.168.25.2]

TASK [geerlingguy.solr : Ensure solr is started and enabled on boot if configured.] *****************************************
fatal: [192.168.25.2]: FAILED! => {"changed": false, "msg": "Unable to enable service solr: solr.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable solr\nupdate-rc.d: error: solr Default-Start contains no runlevels, aborting.\n"}
        to retry, use: --limit @/home/aaron/gizra/****_solr/****_search_playbook/main.retry
```

Most likely root cause:
https://serverfault.com/a/849508

**Comment by AronNovak** [comment]
For the record, if i specify the version and I make sure that only Java 8 is installed, it works. so the following playbook finishes without error:
```yml
- hosts: '192.168.25.2'
  remote_user: root
  roles:
    - role: geerlingguy.java
      java_packages:
        - openjdk-8-jdk
    - role: geerlingguy.solr
      solr_version: "6.6.3"
      solr_filename: "solr-6.6.3"
```
